* Upgrade `python` image from `3.9.1` to `3.9`
